# Generated by Django 5.1.4 on 2024-12-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscard',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='text_color',
        ),
        migrations.AddField(
            model_name='businesscard',
            name='button_background_color',
            field=models.CharField(default='#4CAF50', max_length=7),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='button_hover_background_color',
            field=models.CharField(default='#45a049', max_length=7),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='button_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='buttons_background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='details_background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='details_text_color',
            field=models.CharField(default='#495057', max_length=7),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='logo_background_color',
            field=models.CharField(default='#e9ecef', max_length=7),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='main_background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='profile_border_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
