# Generated by Django 5.1.4 on 2025-01-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_remove_businesscard_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscard',
            name='button_background_color',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='button_hover_background_color',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='button_text_color',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='buttons_background_color',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='details_background_color',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='details_text_color',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='logo_background_color',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='main_background_color',
        ),
        migrations.RemoveField(
            model_name='businesscard',
            name='profile_border_color',
        ),
        migrations.AddField(
            model_name='businesscard',
            name='company_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesscard',
            name='linkdin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='pinterest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='primary_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='reddit',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='seconday_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
