# Generated by Django 5.1.4 on 2025-01-07 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0003_remove_businesscard_button_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
